using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace MTGCatalog.Services
{
    internal class CompareAndTypes
    {
        public class Cores
        {
            public Cores(string corUrl, string corDisplay)
            {
                this.corUrl = corUrl;
                this.corDisplay = corDisplay;
            }

            public string corUrl { get; set; }
            public string corDisplay { get; set; }
        }
        public List<Cores> ShowColors()
        {
            List<Cores> colors = new List<Cores>
        {
            new Cores ("w","Branco"),
            new Cores ("u","Azul"),
            new Cores ("b","Preto"),
            new Cores ("r","Vermelho"),
            new Cores ("g","Verde"),
            new Cores ("c","Incolor")

        };
            return colors;
        }

        public class Compare
        {
            public Compare(string compareUrl, string compareDisplay)
            {
                this.compareUrl = compareUrl;
                this.compareDisplay = compareDisplay;
            }

            public string compareUrl { get; set; }
            public string compareDisplay { get; set; }
        }
        public List<Compare> ShowCompare()
        {
            List<Compare> compare = new List<Compare>
        {
            new Compare ("=","Igual a"),
            new Compare ("!=","Diferente de"),
            new Compare (">=","Maior/igual a"),
            new Compare (">", "Maior que"),
            new Compare ("<=","Menor/igual a"),
            new Compare ("<", "Menor que")
        };
            return compare;

        }

        public class ColorIndic
        {
            public ColorIndic(string colorIndicUrl, string colorIndicDisplay)
            {
                this.colorIndicUrl = colorIndicUrl;
                this.colorIndicDisplay = colorIndicDisplay;
            }

            public string colorIndicUrl { get; set; }
            public string colorIndicDisplay { get; set; }
        }
        public List<ColorIndic> ShowColorIndic()
        {
            List<ColorIndic> indic = new List<ColorIndic>
        {
            new ColorIndic ("=","Só essas cores"),
            new ColorIndic (":","Com essas cores"),
            new ColorIndic ("<=","Em sua maioria")
        };
            return indic;
        }

        public class Types
        {
            public Types(string typeUrl, string typeDisplay)
            {
                this.typeUrl = typeUrl;
                this.typeDisplay = typeDisplay;
            }

            public string typeUrl { get; set; }
            public string typeDisplay { get; set; }
        }
        public List<Types> ShowTypes()
        {
            List<Types> types = new List<Types>
        {
            new Types("artifact","   Artifact"),
new Types("attraction","Attraction"),
new Types("blood","Blood"),
new Types("clue","Clue"),
new Types("contraption","Contraption"),
new Types("equipment","Equipment"),
new Types("food","Food"),
new Types("fortification","Fortification"),
new Types("gold","Gold"),
new Types("powerstone","Powerstone"),
new Types("treasure","Treasure"),
new Types("vehicle","Vehicle"),
new Types("enchantment","   Enchantment"),
new Types("aura","Aura"),
new Types("background","Background"),
new Types("cartouche","Cartouche"),
new Types("class","Class"),
new Types("curse","Curse"),
new Types("rune","Rune"),
new Types("saga","Saga"),
new Types("shard","Shard"),
new Types("shrine","Shrine"),
new Types("land","   Land"),
new Types("cloud","Cloud"),
new Types("desert","Desert"),
new Types("forest","Forest"),
new Types("gate","Gate"),
new Types("island","Island"),
new Types("lair","Lair"),
new Types("locus","Locus"),
new Types("mine","Mine"),
new Types("mountain","Mountain"),
new Types("plains","Plains"),
new Types("power-plant","Power-Plant"),
new Types("swamp","Swamp"),
new Types("tower","Tower"),
new Types("urza's","Urza's"),
new Types("spell","   Spell"),
new Types("adventure","Adventure"),
new Types("arcane","Arcane"),
new Types("lesson","Lesson"),
new Types("trap","Trap"),
new Types("planeswalker","   Planeswalker"),
new Types("abian","Abian"),
new Types("ajani","Ajani"),
new Types("aminatou","Aminatou"),
new Types("angrath","Angrath"),
new Types("arlinn","Arlinn"),
new Types("ashiok","Ashiok"),
new Types("b.o.b","B.O.B."),
new Types("bahamut","Bahamut"),
new Types("basri","Basri"),
new Types("bolas","Bolas"),
new Types("calix","Calix"),
new Types("chandra","Chandra"),
new Types("comet","Comet"),
new Types("dack","Dack"),
new Types("dakkon","Dakkon"),
new Types("daretti","Daretti"),
new Types("davriel","Davriel"),
new Types("dihada","Dihada"),
new Types("domri","Domri"),
new Types("dovin","Dovin"),
new Types("duck","Duck"),
new Types("dungeon","Dungeon"),
new Types("ellywick","Ellywick"),
new Types("elminster","Elminster"),
new Types("elspeth","Elspeth"),
new Types("ersta","Ersta"),
new Types("estrid","Estrid"),
new Types("freyalise","Freyalise"),
new Types("garruk","Garruk"),
new Types("gideon","Gideon"),
new Types("grist","Grist"),
new Types("huatli","Huatli"),
new Types("inzerva","Inzerva"),
new Types("jace","Jace"),
new Types("jared","Jared"),
new Types("jaya","Jaya"),
new Types("jeska","Jeska"),
new Types("kaito","Kaito"),
new Types("karn","Karn"),
new Types("kasmina","Kasmina"),
new Types("kaya","Kaya"),
new Types("kiora","Kiora"),
new Types("koth","Koth"),
new Types("liliana","Liliana"),
new Types("lolth","Lolth"),
new Types("lukka","Lukka"),
new Types("master","Master"),
new Types("minsc","Minsc"),
new Types("mordenkainen","Mordenkainen"),
new Types("nahiri","Nahiri"),
new Types("narset","Narset"),
new Types("niko","Niko"),
new Types("nissa","Nissa"),
new Types("nixilis","Nixilis"),
new Types("oko","Oko"),
new Types("ral","Ral"),
new Types("rowan","Rowan"),
new Types("saheeli","Saheeli"),
new Types("samut","Samut"),
new Types("sarkhan","Sarkhan"),
new Types("serra","Serra"),
new Types("savitri","Savitri"),
new Types("sorin","Sorin"),
new Types("szat","Szat"),
new Types("tamiyo","Tamiyo"),
new Types("tasha","Tasha"),
new Types("teferi","Teferi"),
new Types("teyo","Teyo"),
new Types("tezzeret","Tezzeret"),
new Types("tibalt","Tibalt"),
new Types("tyvar","Tyvar"),
new Types("ugin","Ugin"),
new Types("urza","Urza"),
new Types("venser","Venser"),
new Types("vivien","Vivien"),
new Types("vraska","Vraska"),
new Types("will","Will"),
new Types("windgrace","Windgrace"),
new Types("wrenn","Wrenn"),
new Types("xenagros","Xenagros"),
new Types("yanggu","Yanggu"),
new Types("yanling","Yanling"),
new Types("zariel","Zariel"),
new Types("creature","   Creature"),
new Types("advisor","Advisor"),
new Types("aetherborn","Aetherborn"),
new Types("alicorn","Alicorn"),
new Types("alien","Alien"),
new Types("ally","Ally"),
new Types("angel","Angel"),
new Types("antelope","Antelope"),
new Types("ape","Ape"),
new Types("archer","Archer"),
new Types("archon","Archon"),
new Types("army","Army"),
new Types("art","Art"),
new Types("artificer","Artificer"),
new Types("assassin","Assassin"),
new Types("assembly-worker","Assembly-Worker"),
new Types("astartes","Astartes"),
new Types("atog","Atog"),
new Types("aurochs","Aurochs"),
new Types("autobot","Autobot"),
new Types("avatar","Avatar"),
new Types("arza","Arza"),
new Types("baddest","Baddest,"),
new Types("badger","Badger"),
new Types("balloon","Balloon"),
new Types("barbarian","Barbarian"),
new Types("bard","Bard"),
new Types("basilisk","Basilisk"),
new Types("bat","Bat"),
new Types("bear","Bear"),
new Types("beast","Beast"),
new Types("beaver","Beaver"),
new Types("beeble","Beeble"),
new Types("beholder","Beholder"),
new Types("berserker","Berserker"),
new Types("biggest","Biggest,"),
new Types("bird","Bird"),
new Types("blinkmoth","Blinkmoth"),
new Types("boar","Boar"),
new Types("brainiac","Brainiac"),
new Types("bringer","Bringer"),
new Types("brushwagg","Brushwagg"),
new Types("bureaucrat","Bureaucrat"),
new Types("c'tan","C'Tan"),
new Types("camarid","Camarid"),
new Types("camel","Camel"),
new Types("caribou","Caribou"),
new Types("carrier","Carrier"),
new Types("cat","Cat"),
new Types("centaur","Centaur"),
new Types("cephalid","Cephalid"),
new Types("chameleon","Chameleon"),
new Types("chicken","Chicken"),
new Types("child","Child"),
new Types("chimera","Chimera"),
new Types("citizen","Citizen"),
new Types("clamfolk","Clamfolk"),
new Types("cleric","Cleric"),
new Types("clown","Clown"),
new Types("cockatrice","Cockatrice"),
new Types("construc","Construc"),
new Types("cow","Cow"),
new Types("coward","Coward"),
new Types("crab","Crab"),
new Types("crocodile","Crocodile"),
new Types("custodes","Custodes"),
new Types("cyborg","Cyborg"),
new Types("cyclops","Cyclops"),
new Types("dauthi","Dauthi"),
new Types("deer","Deer"),
new Types("demigod","Demigod"),
new Types("demon","Demon"),
new Types("deserter","Deserter"),
new Types("designer","Designer"),
new Types("devil","Devil"),
new Types("dinosaur","Dinosaur"),
new Types("djinn","Djinn"),
new Types("dog","Dog"),
new Types("donkey","Donkey"),
new Types("dragon","Dragon"),
new Types("drake","Drake"),
new Types("dreadnought","Dreadnought"),
new Types("drone","Drone"),
new Types("druid","Druid"),
new Types("dryad","Dryad"),
new Types("dwarf","Dwarf"),
new Types("efreet","Efreet"),
new Types("egg","Egg"),
new Types("elder","Elder"),
new Types("eldrazi","Eldrazi"),
new Types("elemental","Elemental"),
new Types("elemental","Elemental?"),
new Types("elephant","Elephant"),
new Types("elf","Elf"),
new Types("elk","Elk"),
new Types("elves","Elves"),
new Types("employee","Employee"),
new Types("etiquette","Etiquette"),
new Types("eye","Eye"),
new Types("faerie","Faerie"),
new Types("ferret","Ferret"),
new Types("fish","Fish"),
new Types("flagbearer","Flagbearer"),
new Types("fox","Fox"),
new Types("fractal","Fractal"),
new Types("frog","Frog"),
new Types("fungus","Fungus"),
new Types("gamer","Gamer"),
new Types("gargoyle","Gargoyle"),
new Types("germ","Germ"),
new Types("giant","Giant"),
new Types("gith","Gith"),
new Types("gnoll","Gnoll"),
new Types("gnome","Gnome"),
new Types("goat","Goat"),
new Types("goblin","Goblin"),
new Types("god","God"),
new Types("golem","Golem"),
new Types("gorgon","Gorgon"),
new Types("grandchild","Grandchild"),
new Types("graveborn","Graveborn"),
new Types("gremlin","Gremlin"),
new Types("griffin","Griffin"),
new Types("guest","Guest"),
new Types("gus","Gus"),
new Types("hag","Hag"),
new Types("halfling","Halfling"),
new Types("hamster","Hamster"),
new Types("harpy","Harpy"),
new Types("hatficer","Hatficer"),
new Types("head","Head"),
new Types("hellion","Hellion"),
new Types("hero","Hero"),
new Types("hippo","Hippo"),
new Types("hippogriff","Hippogriff"),
new Types("homarid","Homarid"),
new Types("homunculus","Homunculus"),
new Types("horne","Horne"),
new Types("horror","Horror"),
new Types("horse","Horse"),
new Types("human","Human"),
new Types("hydra","Hydra"),
new Types("hyena","Hyena"),
new Types("illusion","Illusion"),
new Types("imp","Imp"),
new Types("incarnation","Incarnation"),
new Types("inkling","Inkling"),
new Types("inquisitor","Inquisitor"),
new Types("insect","Insect"),
new Types("jackal","Jackal"),
new Types("jellyfish","Jellyfish"),
new Types("juggernaut","Juggernaut"),
new Types("kangaroo","Kangaroo"),
new Types("kavu","Kavu"),
new Types("killbot","Killbot"),
new Types("kirin","Kirin"),
new Types("kithkin","Kithkin"),
new Types("knight","Knight"),
new Types("kobold","Kobold"),
new Types("kor","Kor"),
new Types("kraken","Kraken"),
new Types("lady","Lady"),
new Types("lamia","Lamia"),
new Types("lammasu","Lammasu"),
new Types("leech","Leech"),
new Types("leviathan","Leviathan"),
new Types("lhurgoyf","Lhurgoyf"),
new Types("lici","Lici"),
new Types("lizard","Lizard"),
new Types("lobster","Lobster"),
new Types("mammoth","Mammoth"),
new Types("manticore","Manticore"),
new Types("masticore","Masticore"),
new Types("mercenary","Mercenary"),
new Types("merfolk","Merfolk"),
new Types("metathran","Metathran"),
new Types("mime","Mime"),
new Types("minion","Minion"),
new Types("minotaur","Minotaur"),
new Types("mole","Mole"),
new Types("monger","Monger"),
new Types("mongoose","Mongoose"),
new Types("monk","Monk"),
new Types("monkey","Monkey"),
new Types("moonfolk","Moonfolk"),
new Types("mouse","Mouse"),
new Types("mummy","Mummy"),
new Types("mutant","Mutant"),
new Types("myr","Myr"),
new Types("mystic","Mystic"),
new Types("naga","Naga"),
new Types("nastiest","Nastiest,"),
new Types("nautilus","Nautilus"),
new Types("necron","Necron"),
new Types("nephilim","Nephilim"),
new Types("nightmare","Nightmare"),
new Types("nightstalker","Nightstalker"),
new Types("ninja","Ninja"),
new Types("noble","Noble"),
new Types("noggle","Noggle"),
new Types("nomad","Nomad"),
new Types("nymph","Nymph"),
new Types("octopus","Octopus"),
new Types("ogre","Ogre"),
new Types("ooze","Ooze"),
new Types("orb","Orb"),
new Types("orc","Orc"),
new Types("orgg","Orgg"),
new Types("otter","Otter"),
new Types("ouphe","Ouphe"),
new Types("ox","Ox"),
new Types("oyster","Oyster"),
new Types("pangolin","Pangolin"),
new Types("paratrooper","Paratrooper"),
new Types("peasant","Peasant"),
new Types("pegasus","Pegasus"),
new Types("pentavite","Pentavite"),
new Types("performer","Performer"),
new Types("pest","Pest"),
new Types("phelddagrif","Phelddagrif"),
new Types("phoenix","Phoenix"),
new Types("phyrexian","Phyrexian"),
new Types("pilot","Pilot"),
new Types("pincher","Pincher"),
new Types("pirate","Pirate"),
new Types("plant","Plant"),
new Types("porcupine","Porcupine"),
new Types("praetor","Praetor"),
new Types("primarch","Primarch"),
new Types("prism","Prism"),
new Types("processor","Processor"),
new Types("proper","Proper"),
new Types("rabbit","Rabbit"),
new Types("raccoon","Raccoon"),
new Types("ranger","Ranger"),
new Types("rat","Rat"),
new Types("rebel","Rebel"),
new Types("reflection","Reflection"),
new Types("reveler","Reveler"),
new Types("rhino","Rhino"),
new Types("rigger","Rigger"),
new Types("robot","Robot"),
new Types("rogue","Rogue"),
new Types("sable","Sable"),
new Types("salamander","Salamander"),
new Types("samurai","Samurai"),
new Types("sand","Sand"),
new Types("saproling","Saproling"),
new Types("satyr","Satyr"),
new Types("scarecrow","Scarecrow"),
new Types("scientist","Scientist"),
new Types("scion","Scion"),
new Types("scorpion","Scorpion"),
new Types("scout","Scout"),
new Types("sculpture","Sculpture"),
new Types("serf","Serf"),
new Types("serpent","Serpent"),
new Types("servo","Servo"),
new Types("shade","Shade"),
new Types("shaman","Shaman"),
new Types("shapeshifter","Shapeshifter"),
new Types("shark","Shark"),
new Types("sheep","Sheep"),
new Types("ship","Ship"),
new Types("siren","Siren"),
new Types("skeleton","Skeleton"),
new Types("slith","Slith"),
new Types("sliver","Sliver"),
new Types("slug","Slug"),
new Types("snake","Snake"),
new Types("soldier","Soldier"),
new Types("soltari","Soltari"),
new Types("spawn","Spawn"),
new Types("specter","Specter"),
new Types("spellshaper","Spellshaper"),
new Types("sphinx","Sphinx"),
new Types("spider","Spider"),
new Types("spike","Spike"),
new Types("spirit","Spirit"),
new Types("splinter","Splinter"),
new Types("sponge","Sponge"),
new Types("spy","Spy"),
new Types("squid","Squid"),
new Types("squirrel","Squirrel"),
new Types("starfish","Starfish"),
new Types("sarrakar","Sarrakar"),
new Types("survivor","Survivor"),
new Types("teddy","Teddy"),
new Types("tentacle","Tentacle"),
new Types("tetravite","Tetravite"),
new Types("thalakos","Thalakos"),
new Types("the","The"),
new Types("thoper","Thoper"),
new Types("thrull","Thrull"),
new Types("tiefling","Tiefling"),
new Types("townsfolk","Townsfolk"),
new Types("treefolk","Treefolk"),
new Types("trilobite","Trilobite"),
new Types("triskelavite","Triskelavite"),
new Types("troll","Troll"),
new Types("turtle","Turtle"),
new Types("tyranid","Tyranid"),
new Types("unicorn","Unicorn"),
new Types("vampire","Vampire"),
new Types("vampyre","Vampyre"),
new Types("vedalken","Vedalken"),
new Types("viashino","Viashino"),
new Types("villain","Villain"),
new Types("volver","Volver"),
new Types("waiter","Waiter"),
new Types("wall","Wall"),
new Types("walrus","Walrus"),
new Types("warlock","Warlock"),
new Types("warrior","Warrior"),
new Types("wasp","Wasp"),
new Types("weird","Weird"),
new Types("werewolf","Werewolf"),
new Types("whale","Whale"),
new Types("wizard","Wizard"),
new Types("wolf","Wolf"),
new Types("wolverine","Wolverine"),
new Types("wombat","Wombat"),
new Types("worm","Worm"),
new Types("wraith","Wraith"),
new Types("wrestler","Wrestler"),
new Types("wurm","Wurm"),
new Types("yeti","Yeti"),
new Types("zombie","Zombie"),
new Types("zubera","Zubera"),
new Types("planar","   Planar"),
new Types("alara","Alara"),
new Types("arkhos","Arkhos"),
new Types("azgol","Azgol"),
new Types("belenon","Belenon"),
new Types("bola's-meditation-realm","Bola's Meditation Realm"),
new Types("dominaria","Dominaria"),
new Types("equilor","Equilor"),
new Types("ergamon","Ergamon"),
new Types("fabacin","Fabacin"),
new Types("innistrad","Innistrad"),
new Types("iquatana","Iquatana"),
new Types("ir","Ir"),
new Types("kaldheim","Kaldheim"),
new Types("kamigawa","Kamigawa"),
new Types("karsus","Karsus"),
new Types("kephalai","Kephalai"),
new Types("kinshala","Kinshala"),
new Types("kolbahan","Kolbahan"),
new Types("kyneth","Kyneth"),
new Types("lorwyn","Lorwyn"),
new Types("luvion","Luvion"),
new Types("mercadia","Mercadia"),
new Types("mirrodin","Mirrodin"),
new Types("moag","Moag"),
new Types("mongseng","Mongseng"),
new Types("muraganda","Muraganda"),
new Types("new-phyrexia","New Phyrexia"),
new Types("phyrexia","Phyrexia"),
new Types("pyrulea","Pyrulea"),
new Types("rabiah","Rabiah"),
new Types("rath","Rath"),
new Types("ravnica","Ravnica"),
new Types("regatha","Regatha"),
new Types("segovia","Segovia"),
new Types("serra's-realm","Serra's Realm"),
new Types("shadowmoor","Shadowmoor"),
new Types("shandalar","Shandalar"),
new Types("ulgrotha","Ulgrotha"),
new Types("valla","Valla"),
new Types("vryn","Vryn"),
new Types("wildfire","Wildfire"),
new Types("xerex","Xerex"),
new Types("zendikar","Zendikar")
        };
            return types;
        }
    }
}